import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Provider from "@/context/provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
      <body
        className={` antialiased`}
      >
        {children}
      </body>

      
      </Provider>
    </html>
  );
}
